"""empty message

Revision ID: 71c24775118e
Revises: ffdc0a98111c
Create Date: 2021-08-24 15:19:33.925452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c24775118e'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_foil', sa.Float(), nullable=True),
    sa.Column('small_url', sa.String(length=130), nullable=False),
    sa.Column('img_url', sa.String(length=130), nullable=False),
    sa.Column('art_img', sa.String(length=130), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
