"""deckId attached to comment model

Revision ID: 39e3e494c258
Revises: 5f967f448e95
Create Date: 2021-09-05 16:31:26.784485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e3e494c258'
down_revision = '5f967f448e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('deckId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'decks', ['deckId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'deckId')
    # ### end Alembic commands ###
