"""Added Deck table and relationship to Card table

Revision ID: a53c9e29e7df
Revises: 71c24775118e
Create Date: 2021-08-26 11:05:25.391058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53c9e29e7df'
down_revision = '71c24775118e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('commander', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commander'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decks')
    # ### end Alembic commands ###
